
var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var db = require('../db');

//???router.use(bodyParser.urlencoded({ extended: true }));
// parse incoming request bodies in a middleware before your handlers and makes them available under req.body
router.use(bodyParser.json());

// get all members
router.get('/', function (req, res) {
    console.log('request: ' + req.method + ' all members');
    db(res, 'select * from member order by surname, name');
});

// get one member by id
router.get('/:id', function (req, res) {
    console.log('request: ' + req.method + ' member with id ' + req.params.id);
    db(res, 'select * from member where id=?', req.params.id);
});

// get one member by baf id
router.get('/baf/:bafid', function (req, res) {
    console.log('request: ' + req.method + ' member with baf id ' + req.params.bafid);
    db(res, 'select * from member where baf_id=?', req.params.bafid);
});

// search members by name
router.get('/search/:name', function (req, res) {
    console.log('request: ' + req.method + ' search members with name ' + req.params.name);
    db(res, 'select * from member where surname like ? or name like ?', ['%'+req.params.name+'%','%'+req.params.name+'%']);
});

// store a new member (id is generated by database)
router.post('/', function (req, res) {
    console.log('request: ' + req.method + ' member with data: ' + JSON.stringify(req.body));
    var data = req.body;
    db(res, 'insert into member set ?', data);
});

// update an existing member
router.put('/', function (req, res) {
    console.log('request: ' + req.method + ' member with data: ' + JSON.stringify(req.body));
    var data = req.body;
    db(res, 'update member set ? where id=?', [data, data.id]);
});

// delete one member by id
router.delete('/:id', function (req, res) {
    console.log('request: ' + req.method + ' member with id ' + req.params.id);
    db(res, 'delete from member where id=?', req.params.id);
});

module.exports = router;
