var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var db = require('../db');

// get all members registered for the event with id
router.get('/:id', function (req, res) {
    console.log('request: ' + req.method + ' all members for event with id ' + req.params.id);
    db(res, 'select distinct m.* from member m, registration r where m.id=r.fk_member and r.fk_event=?', req.params.id);
});

// store a new registration (id is generated by database)
router.post('/', function (req, res) {
    console.log('request: ' + req.method + ' registration with data: ' + JSON.stringify(req.body));
    var data = req.body;
    db(res, 'insert into registration set ?', data);
});

module.exports = router;
